
DEFAULT = [

]

ADMIN = [
    'page_list',
    'page_get',
    'page_create',
    'page_update',
    'page_delete',
    'dashboard',
    'unstable_blocks',
    'list_blocks',
    'get_blocks',
    'block_stable_update',
    'search',
    'page_get_content_page',
    'send_message_contact_us',
    'get_lang_text',

    'application_setting_get',
    'application_setting_update',

    'variation_list',
    'variation_get',
    'variation_view',
    'variation_create',
    'variation_update',
    'variation_delete',
    'variation_summary',
    'variation_get_genotype',

    'variation_block_list',
    'variation_block_get',
    'variation_block_create',
    'variation_block_update',
    'variation_block_delete',
    'variation_block_helper',

    'variation_block_version_get',
    'variation_block_version_list',
    'variation_block_version_update',
    'variation_block_version_delete',
    'variation_block_version_active',

    'variation_block_pub_version_get',
    'variation_block_pub_version_list',
    'variation_block_pub_version_update',
    'variation_block_pub_version_delete',

    'variation_block_eff_version_get',
    'variation_block_eff_version_list',
    'variation_block_eff_version_update',
    'variation_block_eff_version_delete',

    'variation_block_alias_version_get',
    'variation_block_alias_version_list',
    'variation_block_alias_version_update',
    'variation_block_alias_version_delete',

    'variation_block_fre_version_get',
    'variation_block_fre_version_list',
    'variation_block_fre_version_update',
    'variation_block_fre_version_delete',

    'variation_block_infobox_version_get',
    'variation_block_infobox_version_list',
    'variation_block_infobox_version_update',
    'variation_block_infobox_version_delete',

    'gene_list',
    'gene_get',
    'gene_view',
    'gene_create',
    'gene_update',
    'gene_delete',
    'gene_summary',

    'gene_block_list',
    'gene_block_get',
    'gene_block_create',
    'gene_block_update',
    'gene_block_delete',
    'gene_block_helper',

    'gene_block_version_get',
    'gene_block_version_list',
    'gene_block_version_update',
    'gene_block_version_delete',
    'gene_block_version_active',

    'gene_block_pub_version_get',
    'gene_block_pub_version_list',
    'gene_block_pub_version_update',
    'gene_block_pub_version_delete',
    'gene_block_pub_version_active',

    'gene_block_alias_version_get',
    'gene_block_alias_version_list',
    'gene_block_alias_version_update',
    'gene_block_alias_version_delete',
    'gene_block_alias_version_active',

    'gene_block_eff_version_get',
    'gene_block_eff_version_list',
    'gene_block_eff_version_update',
    'gene_block_eff_version_delete',
    'gene_block_eff_version_active',

    'gene_block_infobox_version_get',
    'gene_block_infobox_version_list',
    'gene_block_infobox_version_update',
    'gene_block_infobox_version_delete',
    'gene_block_infobox_version_active',

    'disease_list',
    'disease_get',
    'disease_view',
    'disease_create',
    'disease_update',
    'disease_delete',
    'disease_summary',

    'disease_block_list',
    'disease_block_get',
    'disease_block_create',
    'disease_block_update',
    'disease_block_delete',
    'disease_block_helper',

    'disease_block_version_get',
    'disease_block_version_list',
    'disease_block_version_update',
    'disease_block_version_delete',
    'disease_block_version_active',

    'disease_block_pub_version_get',
    'disease_block_pub_version_list',
    'disease_block_pub_version_update',
    'disease_block_pub_version_delete',
    'disease_block_pub_version_active',

    'disease_block_alias_version_get',
    'disease_block_alias_version_list',
    'disease_block_alias_version_update',
    'disease_block_alias_version_delete',
    'disease_block_alias_version_active',

    'trait_list',
    'trait_get',
    'trait_view',
    'trait_create',
    'trait_update',
    'trait_delete',
    'trait_summary',

    'trait_block_list',
    'trait_block_get',
    'trait_block_create',
    'trait_block_update',
    'trait_block_delete',
    'trait_block_helper',


    'trait_block_version_get',
    'trait_block_version_list',
    'trait_block_version_update',
    'trait_block_version_delete',
    'trait_block_version_active',

    'trait_block_pub_version_get',
    'trait_block_pub_version_list',
    'trait_block_pub_version_update',
    'trait_block_pub_version_delete',
    'trait_block_pub_version_active',

    'trait_block_alias_version_get',
    'trait_block_alias_version_list',
    'trait_block_alias_version_update',
    'trait_block_alias_version_delete',
    'trait_block_alias_version_active',

    'treatment_list',
    'treatment_get',
    'treatment_view',
    'treatment_create',
    'treatment_update',
    'treatment_delete',
    'treatment_summary',

    'treatment_block_list',
    'treatment_block_get',
    'treatment_block_create',
    'treatment_block_update',
    'treatment_block_delete',
    'treatment_block_helper',

    'treatment_block_version_get',
    'treatment_block_version_list',
    'treatment_block_version_update',
    'treatment_block_version_delete',
    'treatment_block_version_active',

    'treatment_block_pub_version_get',
    'treatment_block_pub_version_list',
    'treatment_block_pub_version_update',
    'treatment_block_pub_version_delete',
    'treatment_block_pub_version_active',

    'treatment_block_alias_version_get',
    'treatment_block_alias_version_list',
    'treatment_block_alias_version_update',
    'treatment_block_alias_version_delete',
    'treatment_block_alias_version_active',

    'load_comment',
    'reply_comment',
    'like_comment',
    'dislike_comment',
    'submit_comment',
    'comment_list',
    'comment_get',
    'comment_create',
    'comment_update',
    'comment_delete',

    'variation_block_eff_version_active',
    'variation_block_pub_version_active',

    'language_list',
    'language_get',
    'language_create',
    'language_update',
    'language_delete',

    'text_block_list',
    'text_block_get',
    'text_block_create',
    'text_block_update',
    'text_block_delete',

    'email_subscribe_list',
    'email_subscribe_get',
    'email_subscribe_create',
    'email_subscribe_update',
    'email_subscribe_delete',
]
