# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationBlockDisgenetDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('pubmedid', models.CharField(default='', max_length=50)),
                ('sentence', models.TextField(default='')),
                ('variation_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.VariationBlock')),
            ],
        ),
        migrations.CreateModel(
            name='VariationBlockDisgenetDiseasesVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(choices=[(b'admin', b'Admin'), (b'anonymous', b'Anonymous')], default='', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('version_status', models.CharField(choices=[(b'pending', b'Pending'), (b'approved', b'Approved'), (b'denied', b'Denied')], default='', max_length=50)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_stable', models.BooleanField(default=False)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Variation')),
                ('variation_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.VariationBlock')),
            ],
        ),
        migrations.AlterField(
            model_name='variationblockeffect',
            name='popcode',
            field=models.CharField(choices=[{b'id': b'AFR', b'label': b'African'}, {b'id': b'AMR', b'label': b'American'}, {b'id': b'EUR', b'label': b'European'}, {b'id': b'EAS', b'label': b'East Asian'}, {b'id': b'SAS', b'label': b'South Asian'}, {b'id': b'ACB', b'label': b'African Caribbean in Barbados'}, {b'id': b'TSI', b'label': b'Toscani in Italy'}, {b'id': b'BEB', b'label': b'Bengali in Bangladesh'}, {b'id': b'PEL', b'label': b'Peruvian in Lima, Peru'}, {b'id': b'LWK', b'label': b'Luhya in Webuye, Kenya'}, {b'id': b'MSL', b'label': b'Mende in Sierra Leone'}, {b'id': b'GBR', b'label': b'British in England and Scotland'}, {b'id': b'IBS', b'label': b'Iberian populations in Spain'}, {b'id': b'ASW', b'label': b'African Ancestry in Southwest US'}, {b'id': b'KHV', b'label': b'Kinh in Ho Chi Minh City, Vietnam'}, {b'id': b'CEU', b'label': b'Utah residents with Northern and Western European ancestry'}, {b'id': b'YRI', b'label': b'Yoruba in Ibadan, Nigeria'}, {b'id': b'CHB', b'label': b'Han Chinese in Bejing, China'}, {b'id': b'GWD', b'label': b'Gambian in Western Division, The Gambia'}, {b'id': b'STU', b'label': b'Sri Lankan Tamil in the UK'}, {b'id': b'CHS', b'label': b'Southern Han Chinese, China'}, {b'id': b'ESN', b'label': b'Esan in Nigeria'}, {b'id': b'FIN', b'label': b'Finnish in Finland'}, {b'id': b'GIH', b'label': b'Gujarati Indian in Houston, Texas'}, {b'id': b'PJL', b'label': b'Punjabi in Lahore, Pakistan'}, {b'id': b'MXL', b'label': b'Mexican Ancestry in Los Angeles, California'}, {b'id': b'PUR', b'label': b'Puerto Rican in Puerto Rico'}, {b'id': b'ITU', b'label': b'Indian Telugu in the UK'}, {b'id': b'CDX', b'label': b'Chinese Dai in Xishuangbanna, China'}, {b'id': b'JPT', b'label': b'Japanese in Tokyo, Japan'}, {b'id': b'CLM', b'label': b'Colombian in Medellin, Colombia'}], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='variationblockfrequency',
            name='popcode',
            field=models.CharField(choices=[{b'id': b'AFR', b'label': b'African'}, {b'id': b'AMR', b'label': b'American'}, {b'id': b'EUR', b'label': b'European'}, {b'id': b'EAS', b'label': b'East Asian'}, {b'id': b'SAS', b'label': b'South Asian'}, {b'id': b'ACB', b'label': b'African Caribbean in Barbados'}, {b'id': b'TSI', b'label': b'Toscani in Italy'}, {b'id': b'BEB', b'label': b'Bengali in Bangladesh'}, {b'id': b'PEL', b'label': b'Peruvian in Lima, Peru'}, {b'id': b'LWK', b'label': b'Luhya in Webuye, Kenya'}, {b'id': b'MSL', b'label': b'Mende in Sierra Leone'}, {b'id': b'GBR', b'label': b'British in England and Scotland'}, {b'id': b'IBS', b'label': b'Iberian populations in Spain'}, {b'id': b'ASW', b'label': b'African Ancestry in Southwest US'}, {b'id': b'KHV', b'label': b'Kinh in Ho Chi Minh City, Vietnam'}, {b'id': b'CEU', b'label': b'Utah residents with Northern and Western European ancestry'}, {b'id': b'YRI', b'label': b'Yoruba in Ibadan, Nigeria'}, {b'id': b'CHB', b'label': b'Han Chinese in Bejing, China'}, {b'id': b'GWD', b'label': b'Gambian in Western Division, The Gambia'}, {b'id': b'STU', b'label': b'Sri Lankan Tamil in the UK'}, {b'id': b'CHS', b'label': b'Southern Han Chinese, China'}, {b'id': b'ESN', b'label': b'Esan in Nigeria'}, {b'id': b'FIN', b'label': b'Finnish in Finland'}, {b'id': b'GIH', b'label': b'Gujarati Indian in Houston, Texas'}, {b'id': b'PJL', b'label': b'Punjabi in Lahore, Pakistan'}, {b'id': b'MXL', b'label': b'Mexican Ancestry in Los Angeles, California'}, {b'id': b'PUR', b'label': b'Puerto Rican in Puerto Rico'}, {b'id': b'ITU', b'label': b'Indian Telugu in the UK'}, {b'id': b'CDX', b'label': b'Chinese Dai in Xishuangbanna, China'}, {b'id': b'JPT', b'label': b'Japanese in Tokyo, Japan'}, {b'id': b'CLM', b'label': b'Colombian in Medellin, Colombia'}], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='variationblockdisgenetdiseases',
            name='variation_block_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.VariationBlockDisgenetDiseasesVersion'),
        ),
    ]
