# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170516_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationBlockPublicationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024)),
                ('sentence', models.TextField(default='')),
                ('variation_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.VariationBlock')),
            ],
        ),
        migrations.CreateModel(
            name='VariationBlockPublicationTextVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(choices=[(b'admin', b'Admin'), (b'anonymous', b'Anonymous')], default='', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('version_status', models.CharField(choices=[(b'pending', b'Pending'), (b'approved', b'Approved'), (b'denied', b'Denied')], default='', max_length=50)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_stable', models.BooleanField(default=False)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Variation')),
                ('variation_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.VariationBlock')),
            ],
        ),
        migrations.AddField(
            model_name='variationblockpublicationtext',
            name='variation_block_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.VariationBlockPublicationTextVersion'),
        ),
    ]
