# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-24 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_variationassociateddisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAssociatedPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(default='', max_length=50)),
                ('doi', models.CharField(default='', max_length=50)),
                ('pmc', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=1024)),
                ('authors', models.TextField(default='')),
                ('journal', models.CharField(default='', max_length=1024)),
                ('is_disabled', models.BooleanField(default=False)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Gene')),
            ],
        ),
    ]
