# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_geneassociatedpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationgenotype',
            name='source',
            field=models.TextField(default=''),
        ),
    ]
