# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-31 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_variationeffectnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='num_associated_disease',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='num_associated_gene',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='num_associated_publication',
            field=models.IntegerField(default=0),
        ),
    ]
