# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-01 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20170531_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='num_associated_disease',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gene',
            name='num_associated_publication',
            field=models.IntegerField(default=0),
        ),
    ]
